# Generated by Django 5.2.8 on 2025-11-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_login_rename_signup_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
